export interface IAPIPostCreateSoilResponse {}

export type TAPIGetSoilsResponse = Array<{
    id: number;
    name: string;
    properties: {
        ID_TIP: number;
        ID_SOIL: number;
        PODTYP: string;
        NAME_SOIL: string;
        INDEX_MAP: string;
        INDEX_BASE: string;
        LAT: number;
        LON: number;
        LOCATION: string;
        RAION: string;
        AREA_HA: number;
        AREA_KM2: number;
        PERIM_KM: number;
        KR: number;
        POWER: number;
        HUMUS: number;
        CLAY: number;
        PH: number;
        PHOSHORUS: number;
        POTASSIUM: number;
        AGGEGATES: number;
        BULKWEIGHT: number;
        CODE_POWER: number;
        CODE_HUMUS: number;
        CODE_GRAN: number;
        CODE_PH: number;
        CODE_PHOS: number;
        CODE_POTAS: number;
        CODE_AGGRE: number;
        CODE_BULK: number;
        CODE_EROSI: number;
        CODE_SOLON: number;
        CODE_SALIN: number;
        CODE_DRAIN: number;
        KPOWER: number;
        KHUMUS: number;
        KCLAY: number;
        KPH: number;
        KEROSION: number;
        KSOLON: number;
        KSALIN: number;
        KDRAIN: number;
        KSOIL: number;
        UR: number;
        KINDEX2: number;
        ECOL_INDEX: number;
        BALL_POWER: number;
        BALL_HUMUS: number;
        BALL_CLAY: number;
        BONITET: number;
        ENERGO: number;
        KONTR: number;
    };
    geometry: { type: string; coordinates: Array<[number, number]> };
}>;
